[versions]

sqldelightVersion = "1.5.3"

[libraries]

buildscript-sqlDelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelightVersion" }

common-sqlDelight = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelightVersion" }

android-sqlDelight = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelightVersion" }

native-sqlDelight = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelightVersion" }
